export const PARAM_KEY = 'addon_code';
export const STORY_GROUP_DEFAULT_EXPORT_IDENTIFIER =
  '__STORYBOOK_ADDON_CODE_DEFAULT_EXPORT';
export const SOURCE_FILE_IMPORT_IDENTIFIER_PREFIX =
  '__STORYBOOK_ADDON_CODE_SOURCE_FILE_';
